Chuvas ao longo do dia com alguns períodos de melhoria.	'\S\\u\.\v\\a\\js\ \a\\w\ '\l\\o~\.\g\\u\ \d\\u\ '\dZ\\i\.\a\ \k\\o~\ \a\\w\'\g\\u~\\s\ \p\\e\'\r\\i\\o\.\d\\u\\s\ \dZ\\i\ \m\\e\.\L\\o\'\r\\i\.\a\
Tempo nublado com chuvas isoladas ao longo do dia.	'\t\\e~\.\p\\u\ \n\\u\'\b\\l\\a\.\d\\u\ \k\\o~\ '\S\\u\.\v\\a\\js\ \i\.\z\\o\'\l\\a\.\d\\a\\js\ \a\\w\ '\l\\o~\.\g\\u\ \d\\u\ '\dZ\\i\.\a\
Predomínio de sol, apenas com pouca variação de nuvens.	\p\\r\\e\.\d\\o\'\m\\i\\n\\i\\u\ \dZ\\i\ '\s\\O\\w\\pau\ \a\'\p\\e~\.\n\\a\\js\ \k\\o~\ '\p\\ow\.\k\\a\ \v\\a\.\r\\i\.\a\'\s\\a~\\w~\ \dZ\\i\ '\n\\u\.\v\\e~\\s\
Céu claro com predomínio de sol ao longo do dia.	'\s\\E\\u\ '\k\\l\\a\.\r\\u\ \k\\o~\ \p\\r\\e\.\d\\o\'\m\\i\\n\\i\\u\ \dZ\\i\ '\s\\O\\w\ \a\\w\ '\l\\o~\.\g\\u\ \d\\u\ '\dZ\\i\.\a\
O frio continua no sul.	\u\ '\f\\r\\i\.\u\ \k\\o~\.\tS\\i~\'\n\\u\.\a\ \n\\u\ '\s\\u\\w\
Nesta quarta feira 5 de agosto, a forte massa de ar frio seguirá atuando no sul do brasil mantendo as temperaturas baixas e a possibilidade de neve nas serras gaúcha e catarinense.	'\n\\E\\s\.\t\\a\ '\k\\w\\a\\X\.\t\\a\ '\f\\ej\.\r\\a\ '\s\\i~\.\k\\u\ \dZ\\i\ \a\'\g\\o\\s\.\t\\u\\pau\ \a\ '\f\\O\\X\.\tS\\i\ '\m\\a\.\s\\a\ \dZ\\i\ \a\\X\ '\f\\r\\i\.\u\ \s\\e\.\g\\i\'\r\\a\ \a\.\t\\u\'\a~\.\d\\u\ \n\\u\ '\s\\u\\w\ \d\\u\ \b\\r\\a\'\z\\i\\w\ \m\\a~\'\t\\e~\.\d\\u\ \a\\js\ \t\\e~\.\p\\e\.\r\\a\'\t\\u\.\r\\a\\js\ '\b\\a\\j\.\S\\a\\js\ \i\ \a\ \p\\o\.\s\\i\.\b\\i\.\l\\i\'\d\\a\.\dZ\\i\ \dZ\\i\ '\n\\E\.\v\\i\ \n\\a\\js\ '\s\\E\.\R\\a\\js\ \g\\a\'\u\\S\\a\ \i\ \k\\a\.\t\\a\.\r\\i~\'\n\\e~\.\s\\i\
Uma frente fria de fraca intensidade manterá o tempo instável com chuva no sul do Rio de Janeiro e em parte de São Paulo.	\u~\.\m\\a\ '\f\\r\\e~\.\tS\\i\ '\f\\r\\i\.\a\ \dZ\\i\ '\f\\r\\a\.\k\\a\ \i~\.\t\\e~\.\s\\i\'\d\\a\.\dZ\\i\ \m\\a~\.\t\\e\'\r\\a\ \u\ '\t\\e~\.\p\\u\ \i~\\s\'\t\\a\.\v\\e\\w\ \k\\o~\ '\S\\u\.\v\\a\ \n\\u\ '\s\\u\\w\ \d\\u\ '\R\\i\.\u\ \dZ\\i\ \Z\\a\'\n\\ej\.\r\\u\ \i\ \e~j~\.\p\\a\\X\.\tS\\i\ '\dZ\\i\ \s\\a~\\w~\ '\p\\a\\u\.\l\\u\
Na faixa litorânea entre o sul do Rio de Janeiro e o nordeste de Santa Catarina o dia ficará chuvoso e os ventos estarão fortes.	\n\\a\ '\f\\a\\j\.\S\\a\ \l\\i\.\t\\o\'\r\\a~\.\n\\e\.\a\ '\e~\.\t\\r\\i\ \u\ '\s\\u\\w\ \d\\u\ '\R\\i\.\u\ \dZ\\i\ \Z\\a\'\n\\ej\.\r\\u\ \i\ \u\ \n\\o\\R\'\d\\E\\s\.\tS\\i\ \dZ\\i\ '\s\\a~\.\t\\a\ \k\\a\.\t\\a\'\r\\i~\.\n\\a\ \u\ '\dZ\\i\.\a\ \f\\i\.\k\\a\'\r\\a\ \S\\u\'\v\\o\.\z\\u\ \i\ \u\\s\ '\v\\e~\.\t\\u\\z\ \e\\s\.\t\\a\'\r\\a~\\w~\ '\f\\O\\X\.\tS\\i\\s\
Espera-se muita nebulosidade e chuva também no sul de Mato Grosso do Sul, Paraná, em Santa Catarina e na faixa leste do Rio Grande do Sul.	\e\\s\'\p\\E\.\r\\a\ \s\\i\ '\m\\u\\j~\.\t\\a\ \n\\e\.\b\\u\.\l\\o\.\z\\i\'\d\\a\.\dZ\\i\ \i\ '\S\\u\.\v\\a\ \t\\a~\'\b\\e~j~\ \n\\u\ '\s\\u\\w\ \dZ\\i\ '\m\\a\.\t\\u\ '\g\\r\\O\.\s\\u\ \d\\u\ '\s\\u\\w\\pau\ \p\\a\.\r\\a\'\n\\a\\pau\ \e~j~\.\s\\a~\.\t\\a\ '\k\\a\.\t\\a\.\r\\i~\.\n\\a\ \i\ \n\\a\ \f\\a\\j\.\S\\a\ '\l\\E\\s\.\tS\\i\ '\d\\u\ \R\\i\.\u\ '\g\\r\\a~\.\dZ\\i\ '\d\\u\ \s\\u\\w\
No Norte do país haverá pancadas de chuva localizadas.	\n\\u\ '\n\\O\\X\.\tS\\i\ \d\\u\ \p\\a\'\i\\js\ \a\.\v\\e\'\r\\a\ \p\\a~\'\k\\a\.\d\\a\\js\ \dZ\\i\ '\S\\u\.\v\\a\ \l\\o\.\k\\a\.\l\\i\'\z\\a\.\d\\a\\js\
O tempo ficará instável no litoral do Nordeste.	\u\ '\t\\e~\.\p\\u\ \f\\i\.\k\\a\'\r\\a\ \i~\\s\'\t\\a\.\v\\e\\w\ \n\\u\ \l\\i\.\t\\o\'\r\\a\\w\ \d\\u\ \n\\o\\R\'\d\\E\\s\.\tS\\i\
Nas demais áreas do país o sol predominará e a umidade relativa do ar estará baixa podendo ficar abaixo dos vinte por cento em algumas localidades do centro-oeste e interior do nordeste.	\n\\a\\js\ \d\\e\'\m\\a\\j\\z\ '\a\.\r\\e\\a\\js\ \d\\u\ \p\\a\'\i\\js\ \u\ '\s\\O\\w\ \p\\r\\e\.\d\\o\.\m\\i~\.\n\\a\'\r\\a\ \i\ \a\ \u~\.\m\\i\'\d\\a\.\dZ\\i\ \R\\e\.\l\\a\'\tS\\i\.\v\\a\ \d\\u\ \a\\r\ \e\\s\.\t\\a\'\r\\a\ '\b\\a\\j\.\S\\a\ \p\\o\'\d\\e~\.\d\\u\ \f\\i\'\k\\a\\r\ \a\'\b\\a\\j\.\S\\u\ \d\\u\\s\ '\v\\i~\.\tS\\i\ \p\\o\\X\ '\s\\e~\.\t\\u\ \e~j~\.\a\\w\.\g\\u~\.\m\\a\\js\ \l\\o\'\k\\a\.\l\\i\.\d\\a\.\dZ\\i\\s\ \d\\u\ \s\\e~\.\t\\r\\u\ '\o\.\E\\s\.\tS\\i\ \i\ \i~\.\t\\e\.\r\\i\.\o\\R\ \d\\u\ \n\\o\\R\.\d\\E\\s\.\tS\\i\
As temperaturas estarão baixas na região sul, em Mato Grosso do Sul e em São Paulo.	\a\\js\ \t\\e~\.\p\\e\.\r\\a\'\t\\u\.\r\\a\\js\ \e\\s\.\t\\a\'\r\\a~\\w~\ '\b\\a\\j\.\S\\a\\js\ \n\\a\ \R\\e\.\Z\\i\'\a~\\w~\ '\s\\u\\w\\pau\ \e~j~\.\m\\a\.\t\\u\ '\g\\r\\O\.\s\\u\ '\d\\u\ \s\\u\\w\ '\i\ \e~j~\.\s\\a~\\w~\ \p\\a\\u\.\l\\u\
